repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.18.4
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]

default_language_version:
  python: python3.11

ci:
  autofix_commit_msg: "style: auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
