name: Release

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Python Semantic Release
      uses: python-semantic-release/python-semantic-release@v8.7.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.5
        
    - name: Update version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        poetry run cz bump --yes
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: steps.tag_version.outputs.tag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.tag }}
        name: Release ${{ steps.tag_version.outputs.tag }}
        body: ${{ steps.tag_version.outputs.changelog }} 